import { useState } from "react";

type CartItem = { id: string; title: string; source_site: string; current_price: number };
const apiUrl = import.meta.env.VITE_API_HTTP_URL ?? "http://127.0.0.1:8000";

export function CartDrawer({ items, onRemove }: { items: CartItem[]; onRemove: (id: string) => void }) {
  const [loadingId, setLoadingId] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const checkout = async (item: CartItem) => { setLoadingId(item.id); setMessage(null); try { const response = await fetch(`${apiUrl}/payment-link`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: item.id }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Unable to create payment link."); window.open(body.payment_link_url, "_blank", "noopener,noreferrer"); setMessage("Razorpay test link opened in a new tab."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create payment link."); } finally { setLoadingId(null); } };
  return <aside className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Your shortlist</p><h2 className="mt-1 text-xl font-bold text-white">Cart · {items.length}</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/15 text-xl">🛒</span></div>{items.length === 0 ? <p className="mt-5 text-sm leading-6 text-slate-400">Add comparison results here. This is a private shortlist, not a retailer checkout.</p> : <ul className="mt-4 space-y-3">{items.map((item) => <li key={item.id} className="rounded-xl bg-black/20 p-3"><p className="text-sm font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.source_site} · ₹{item.current_price.toLocaleString("en-IN")}</p><div className="mt-3 flex gap-3"><button onClick={() => checkout(item)} disabled={loadingId === item.id} className="rounded-lg bg-cyan-300 px-2 py-1 text-xs font-bold text-slate-950 disabled:opacity-50">{loadingId === item.id ? "Creating…" : "Razorpay test checkout"}</button><button onClick={() => onRemove(item.id)} className="text-xs font-bold text-rose-300">Remove</button></div></li>)}</ul>}{message && <p className="mt-4 text-xs leading-5 text-amber-200">{message}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Test-mode only. Payment happens on Razorpay’s hosted page, never inside Pricewise.</p></aside>;
}
