import { FormEvent, useEffect, useState } from "react";
import { CartDrawer } from "./components/CartDrawer";
import { ChatIntake } from "./components/ChatIntake";
import { ProductComparisonGrid } from "./components/ProductComparisonGrid";
import { RecommendationPanel } from "./components/RecommendationPanel";
import { SearchProgress } from "./components/SearchProgress";
import { useChatSocket } from "./hooks/useChatSocket";
import { useSessionStore } from "./store/sessionStore";

export default function App() {
  const [name, setName] = useState("");
  const sessionId = useSessionStore((state) => state.sessionId); const messages = useSessionStore((state) => state.messages); const demoUser = useSessionStore((state) => state.demoUser); const cart = useSessionStore((state) => state.cart); const setUser = useSessionStore((state) => state.setUser); const addToCart = useSessionStore((state) => state.addToCart); const removeFromCart = useSessionStore((state) => state.removeFromCart);
  const { connect, sendMessage, stage, finalResult, error, isConnected } = useChatSocket();
  useEffect(() => { connect(sessionId); }, [connect, sessionId]);
  const signIn = (event: FormEvent) => { event.preventDefault(); if (name.trim()) setUser(name.trim()); };
  if (!demoUser) return <main className="grid min-h-screen place-items-center bg-[#070b16] p-6 text-white"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.045] p-8 shadow-2xl"><p className="text-sm font-bold uppercase tracking-[.3em] text-cyan-300">Pricewise / Demo</p><h1 className="mt-4 text-4xl font-extrabold">Shop with conviction.</h1><p className="mt-4 leading-7 text-slate-400">A live retailer advisor for smarter buying decisions.</p><form onSubmit={signIn} className="mt-8 space-y-3"><input value={name} onChange={(event) => setName(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-white" placeholder="Your name for this demo" /><button className="w-full rounded-xl bg-cyan-300 px-4 py-3 font-bold text-slate-950">Enter workspace →</button></form><p className="mt-4 text-xs text-slate-500">Demo login only — no password or account is created.</p></section></main>;
  return <main className="min-h-screen bg-[#070b16] text-white"><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-cyan-300">Pricewise / Live advisor</p><h1 className="mt-2 text-3xl font-extrabold">Good to see you, {demoUser}.</h1></div><div className="flex items-center gap-3"><button onClick={() => setUser(null)} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-slate-300">Switch demo user</button><span className={`rounded-full px-3 py-2 text-sm font-bold ${isConnected ? "bg-emerald-400/15 text-emerald-300" : "bg-amber-400/15 text-amber-200"}`}>{isConnected ? "● Live connection" : "● Reconnecting"}</span></div></header><section className="grid gap-6 py-8 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><div className="rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-cyan-300/10 via-white/[.03] to-transparent p-7"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">Decision intelligence</p><h2 className="mt-3 text-4xl font-extrabold">Find the right moment to buy.</h2><p className="mt-4 text-lg leading-7 text-slate-400">Real retailers, actual price signals, and a clear decision.</p></div>{error && <div role="alert" className="rounded-2xl border border-rose-400/30 bg-rose-400/10 px-5 py-4 text-sm text-rose-100">{error}</div>}<ChatIntake messages={messages} onSend={sendMessage} disabled={!isConnected} /><SearchProgress stage={stage} />{finalResult && <><RecommendationPanel result={finalResult} /><ProductComparisonGrid products={finalResult.products} onAddToCart={addToCart} /></>}</div><CartDrawer items={cart} onRemove={removeFromCart} /></section></div></main>;
}
